name: Deploy to VPS using PM2

on:
  push:
    branches: [main] # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_PRIVATE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            eval "$(ssh-agent -s)"

            ssh-add /home/romulo/.ssh/github

            cd /home/romulo/apps/viagens-am

            git pull

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22

            npm install
            npm run build

            pm2 restart ecosystem.config.mjs --update-env

            pm2 list
